name: Continuous Delivery

on:
  push:
    tags:
      - 'v*' # e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-35-jdk21
    env:
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
    steps:
      - uses: actions/checkout@v3
      - name: Decode keystore
        run: echo $KEYSTORE_BASE64
      - name: Decode keystore
        run: echo $KEYSTORE_BASE64 | base64 --decode > keystore.jks
      - name: Build AAB
        run: ./gradlew bundleRelease
      - uses: softprops/action-gh-release@v1
        with:
          files: HamsterListAndroid/build/outputs/bundle/release/*.aab
